In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/umangkejriwal1122/Youtube/master/Salary_Data.csv')
data.head(6)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0

In [ ]:
x = data.iloc[:,0].values  ## input(features)
y = data.iloc[:,1].values  ## output(target)

In [ ]:
x

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.2,  3.7,  3.9,
        4. ,  4. ,  4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [ ]:
x = x.reshape(-1,1)
y = y.reshape(-1,1)

In [ ]:
y
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [ ]:
## Splitting the data into training and testing data sets
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20)

In [ ]:
### Create the model
from sklearn.linear_model import LinearRegression
lin = LinearRegression()

In [ ]:
## apply the model
lin.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = lin.predict(xtest)

In [ ]:
y_pred

In [ ]:
ytest

In [ ]:
plt.scatter(xtrain,ytrain,color='green')
plt.plot(xtrain,lin.predict(xtrain),color='blue')
plt.title("Salary vs Experience Training Graph")
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.show()

In [ ]:
plt.scatter(xtest,ytest,color='green')
plt.plot(xtest,lin.predict(xtest),color='blue')
plt.title("Salary vs Experience Testing Graph")
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.show()

In [ ]:
### Result Verification

In [ ]:
### y = mx + c

In [ ]:
lin.coef_  ### value of m

array([[9386.4328057]])

In [ ]:
lin.intercept_  ### value of c

array([25134.88739593])

In [ ]:
9310.92699813 * 1.5 + 25684.12273434

39650.513231535

In [ ]:
9310.92699813 * 4.0 + 25684.12273434

62927.830726860004

In [ ]:
from sklearn.metrics import r2_score
r2_score(ytest,y_pred)

0.9135145360195338